Scheme
{
	"MaxiHudLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"MaxiHudLabel"
		"labelText"			"#MaxiHudLabel"
		"font"				"HudFontSmallBold"
		"xpos"				"r255"
		"ypos"				"r75"
		"zpos"				"7"
		"wide"				"250"
		"tall"				"10"
		"textAlignment"		"east"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override" 	"TanLight"
	}
	"MaxiHudLabelShadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"MaxiHudLabelShadow"
		"labelText"			"#MaxiHudLabel"
		"font"				"HudFontSmallBold"
		"xpos"				"-1"
		"ypos"				"-1"
		"zpos"				"7"
		"wide"				"250"
		"tall"				"10"
		"textAlignment"		"east"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override" 	"Black"
		"pin_to_sibling"	"MaxiHudLabel"
	}
}