"Resource/UI/MainMenuOverride.res"
{
	"SafeMode"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"SafeMode"
		"xpos"					"c155"
		"ypos"					"35"
		"zpos"					"1"
		"wide"					"240"
		"tall"					"380"
		"visible"				"0"
		"PaintBackgroundType"	"2"
		"paintbackground"		"0"
		
		"MaxiHudSettingsText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"MaxiHudSettingsText"
			"labelText"			"MaxiHud Settings"
			"font"				"HudFontSmallBold"
			"xpos"				"6"
			"ypos"				"8"
			"zpos"				"2"
			"wide"				"130"
			"tall"				"15"
			"textAlignment"		"center"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"BackgroundPanel"
		{
			"controlname"	"EditablePanel"
			"wide"			"240"
			"tall"			"380"
			"border"		"MainMenuBGBorder"

			"Panel"
			{
				"controlname"	"CScrollableList"
				"xpos"			"cs-0.5"
				"ypos"			"28"
				"wide"			"230"
				"tall"			"300"
				"proportionaltoparent"	"1"
				"border"		"InnerShadowBorder"
				"paintborder"	"1"
				"bottom_buffer"	"2"

				"ScrollBar"
				{
					"controlname"	"ScrollBar"
					"xpos"			"rs1-1"
					"wide"			"4"
					"proportionaltoparent"	"1"
				}

				"TeamStatusBar" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"TeamStatusBar"
					"xpos"							"4"
					"ypos"							"5"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"48"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Team Status Bar"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine tf_use_match_hud 1"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}

					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine tf_use_match_hud 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}

				"MaxiCross" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"MaxiCross"
					"xpos"							"4"
					"ypos"							"58"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"140"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Enable MaxiCross Presets"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Description1"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Description1"
						"xpos"							"4"
						"ypos"							"20"
						"zpos"							"0"
						"wide"							"210"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"If you have either MaxiCross or MaxiCross+ installed, selecting ''On'' will configure it to its recommended presets. Choosing ''Off'' reverts it back to default."
						"font"							"Default"
						"textAlignment"					"center"
						"wrap"							"1"
						"fgcolor"						"TanLight"
					}

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"50"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_crosshair_scale 20; cl_crosshair_red 236; cl_crosshair_green 227; cl_crosshair_blue 203"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
					
					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"50"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_crosshair_scale 32; cl_crosshair_red 200; cl_crosshair_green 200; cl_crosshair_blue 200"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
					
					"Description2"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Description2"
						"xpos"							"4"
						"ypos"							"80"
						"zpos"							"0"
						"wide"							"210"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Don't have MaxiCross or MaxiCross+ installed?"
						"font"							"Default"
						"textAlignment"					"center"
						"fgcolor"						"TanDark"
					}

					"DownloadButton1"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"DownloadButton1"
						"xpos"			"6"
						"ypos"			"100"
						"zpos"			"1"
						"wide"			"206"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Download MaxiCross"
						"textAlignment"	"center"
						"font"			"HudFontSmallest"
						"Command"		"url https://gamebanana.com/mods/467250"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"

						"defaultBgColor_override"		"TransparentBlack"
					}

					"DownloadButton2"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"DownloadButton2"
						"xpos"			"6"
						"ypos"			"120"
						"zpos"			"1"
						"wide"			"206"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Download MaxiCross+"
						"textAlignment"	"center"
						"font"			"HudFontSmallest"
						"Command"		"url https://gamebanana.com/mods/511274"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"

						"defaultBgColor_override"		"TransparentBlack"
					}
				}

				"CorneredHUD" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"CorneredHUD"
					"xpos"							"4"
					"ypos"							"203"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"48"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Cornered HUD"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_hud_minmode 1"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}

					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_hud_minmode 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}

				"PlayerModel" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"PlayerModel"
					"xpos"							"4"
					"ypos"							"256"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"48"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Player model in HUD"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_hud_playerclass_use_playermodel 1"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}

					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine cl_hud_playerclass_use_playermodel 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}

				"DemoRecording" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"DemoRecording"
					"xpos"							"4"
					"ypos"							"309"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"48"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Demo Recording"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine ds_enable 2"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}

					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine ds_enable 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}

				"Cheats" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"Cheats"
					"xpos"							"4"
					"ypos"							"362"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"48"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Disable Stat Tracking + Enable Cheats"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}
					
					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine sv_cheats 1"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
					
					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"19"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine sv_cheats 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}

				"Safety" ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"Safety"
					"xpos"							"4"
					"ypos"							"415"
					"zpos"							"0"
					"wide"							"218"
					"tall"							"70"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintBackground"				"1"
					"paintBackgroundType"			"2"
					"roundedcorners"				"5"
					"bgcolor_override"				"FooterBGBlack"

					"Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Title"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"218"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Safety Mode"
						"font"							"HudFontSmallest"
						"textAlignment"					"center"
						"fgcolor"						"TanLight"
						"paintbackground"				"1"
						"paintBackgroundType"			"2"
						"roundedcorners"				"3"
						"bgcolor_override"				"StoreGreen"
					}

					"Description"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Description"
						"xpos"							"4"
						"ypos"							"18"
						"zpos"							"0"
						"wide"							"210"
						"tall"							"20"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"labelText"						"Safety Mode mutes the text and voice chat and hides custom sprays and decals."
						"font"							"Default"
						"textAlignment"					"center"
						"wrap"							"1"
						"fgcolor"						"TanLight"
					}						

					"Option1Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option1Button"
						"xpos"			"6"
						"ypos"			"40"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"On"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine voice_enable 0; cl_enable_text_chat 0; cl_spraydisable 1; tf_hide_custom_decals 1"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
					
					"Option2Button"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"Option2Button"
						"xpos"			"112"
						"ypos"			"40"
						"zpos"			"1"
						"wide"			"100"
						"tall"			"25"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		"Off"
						"textAlignment"	"center"
						"font"			"HudFontMediumSmallBold"
						"Command"		"engine voice_enable 1; cl_enable_text_chat 1; cl_spraydisable 0; tf_hide_custom_decals 0"
						"actionsignallevel"    "5"

						"sound_armed"		"ui/buttonrollover.wav"
						"sound_depressed"	"ui/buttonclick.wav"
						"sound_released"	"ui/buttonclickrelease.wav"
					}
				}
			}	
		}

		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"218"
			"ypos"			"9"
			"zpos"			"2"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"engine cl_mainmenu_safemode 0; mat_queue_mode -1"
			"actionsignallevel"    "2"

			"paintbackground"	"0"

			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"

			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}
		}

		"ComingSoonLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"ComingSoonLabel"
			"labelText"			"Customization files will be merged with the MaxiHud Settings menu in v17.0. Coming soon..."
			"font"				"HudFontSmallestBold"
			"xpos"				"20"
			"ypos"				"333"
			"zpos"				"2"
			"wide"				"210"
			"tall"				"40"
			"textAlignment"		"center"
			"wrap"				"1"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
	}
}