"Resource/UI/MainMenuOverride.res"
{
	"SafeMode"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"SafeMode"
		"xpos"					"c155"
		"ypos"					"255"
		"zpos"					"1"
		"wide"					"240"
		"tall"					"160"
		"visible"				"0"
		"PaintBackgroundType"	"2"
		"paintbackground"		"0"
		"border"				"MainMenuBGBorder"
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"215"
			"ypos"			"13"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"engine cl_mainmenu_safemode 0; mat_queue_mode -1"
			"actionsignallevel"    "2"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}
		}
		
		"MaxiHudSettingsText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"MaxiHudSettingsText"
			"labelText"			"MaxiHud Settings"
			"font"				"HudFontMediumSmallBold"
			"xpos"				"40"
			"ypos"				"13"
			"zpos"				"0"
			"wide"				"165"
			"tall"				"15"
			"textAlignment"		"center"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"OnText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"OnText"
			"labelText"			"On"
			"font"				"HudFontSmallest"
			"xpos"				"156"
			"ypos"				"35"
			"zpos"				"0"
			"wide"				"20"
			"tall"				"12"
			"textAlignment"		"center"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"OffText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"OffText"
			"labelText"			"Off"
			"font"				"HudFontSmallest"
			"xpos"				"197"
			"ypos"				"35"
			"zpos"				"0"
			"wide"				"20"
			"tall"				"12"
			"textAlignment"		"center"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"Box"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"Box"
			"xpos"			"10"
			"ypos"			"49"
			"zpos"			"0"
			"wide"			"220"
			"tall"			"2"
			"fillcolor"		"42 39 37 255"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		
		// TEAM STATUS BAR
		//-------------------------------------------------------
	
		"TeamStatusBarText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"TeamStatusBarText"
			"labelText"			"Team status bar"
			"font"				"HudFontSmallest"
			"xpos"				"20"
			"ypos"				"55"
			"zpos"				"0"
			"wide"				"150"
			"tall"				"12"
			"textAlignment"		"west"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}

		"TeamStatusBarOnButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"TeamStatusBarOnButton"
			"xpos"				"160"
			"ypos"				"55"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine tf_use_match_hud 1"
			"actionsignallevel"	"2"

			"paintbackground"	"0"

			"image_drawcolor"	"76 107 34 255"
			"image_armedcolor"	"94 150 49 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}
		
		"TeamStatusBarOffButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"TeamStatusBarOffButton"
			"xpos"				"200"
			"ypos"				"55"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine tf_use_match_hud 0"
			"actionsignallevel"	"2"

			"paintbackground"	"0"

			"image_drawcolor"	"99 36 33 225"
			"image_armedcolor"	"154 30 22 225"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}
		
		// CORNERED HUD
		//-------------------------------------------------------

		"CorneredHUDText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"CorneredHUDText"
			"labelText"			"Cornered HUD"
			"font"				"HudFontSmallest"
			"xpos"				"20"
			"ypos"				"75"
			"zpos"				"0"
			"wide"				"150"
			"tall"				"12"
			"textAlignment"		"west"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"CorneredHUDOnButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"CorneredHUDOnButton"
			"xpos"				"160"
			"ypos"				"75"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine cl_hud_minmode 1"
			"actionsignallevel"	"2"
			
			"paintbackground"	"0"
			
			"image_drawcolor"	"76 107 34 255"
			"image_armedcolor"	"94 150 49 255"
			
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}
		
		"CorneredHUDOffButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"CorneredHUDOffButton"
			"xpos"				"200"
			"ypos"				"75"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine cl_hud_minmode 0"
			"actionsignallevel"	"2"
			
			"paintbackground"	"0"
			
			"image_drawcolor"	"99 36 33 225"
			"image_armedcolor"	"154 30 22 225"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}	
		
		// PLAYER MODEL IN HUD
		//-------------------------------------------------------

		"PlayerModelText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"PlayerModelText"
			"labelText"			"Player model in HUD"
			"font"				"HudFontSmallest"
			"xpos"				"20"
			"ypos"				"95"
			"zpos"				"0"
			"wide"				"150"
			"tall"				"12"
			"textAlignment"		"west"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
		
		"PlayerModelOnButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"PlayerModelOnButton"
			"xpos"				"160"
			"ypos"				"95"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine cl_hud_playerclass_use_playermodel 1"
			"actionsignallevel"	"2"

			"paintbackground"	"0"
		
			"image_drawcolor"	"76 107 34 255"
			"image_armedcolor"	"94 150 49 255"
			
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}

		"PlayerModelOffButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"PlayerModelOffButton"
			"xpos"				"200"
			"ypos"				"95"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine cl_hud_playerclass_use_playermodel 0"
			"actionsignallevel"	"2"
			
			"paintbackground"	"0"
			
			"image_drawcolor"	"99 36 33 225"
			"image_armedcolor"	"154 30 22 225"
			
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}
		
		// DEMO RECORDING
		//-------------------------------------------------------
		
		"DemoRecordingText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"DemoRecordingText"
			"labelText"			"Demo recording"
			"font"				"HudFontSmallest"
			"xpos"				"20"
			"ypos"				"115"
			"zpos"				"0"
			"wide"				"150"
			"tall"				"12"
			"textAlignment"		"west"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}
			
		"DemoRecordingOnButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"DemoRecordingOnButton"
			"xpos"				"160"
			"ypos"				"115"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine ds_enable 2"
			"actionsignallevel"	"2"
			
			"paintbackground"	"0"

			"image_drawcolor"	"76 107 34 255"
			"image_armedcolor"	"94 150 49 255"
		
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}

		"DemoRecordingOffButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"DemoRecordingOffButton"
			"xpos"				"200"
			"ypos"				"115"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine ds_enable 0"
			"actionsignallevel"	"2"

			"paintbackground"	"0"

			"image_drawcolor"	"99 36 33 225"
			"image_armedcolor"	"154 30 22 225"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}	
		
		// STAT TRACKING
		//-------------------------------------------------------
		
		"StatTrackingText"
		{
			"ControlName"		"CExLabel"
			"fieldName"			"StatTrackingText"
			"labelText"			"Stat tracking"
			"font"				"HudFontSmallest"
			"xpos"				"20"
			"ypos"				"135"
			"zpos"				"0"
			"wide"				"150"
			"tall"				"12"
			"textAlignment"		"west"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override" 	"TanLight"
		}

		"StatTrackingOnButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"StatTrackingOnButton"
			"xpos"				"160"
			"ypos"				"135"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine sv_cheats 0"
			"actionsignallevel"	"2"

			"paintbackground"	"0"

			"image_drawcolor"	"76 107 34 255"
			"image_armedcolor"	"94 150 49 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}

		"StatTrackingOffButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"StatTrackingOffButton"
			"xpos"				"200"
			"ypos"				"135"
			"zpos"				"10"
			"wide"				"12"
			"tall"				"12"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labeltext"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"			"engine sv_cheats 1"
			"actionsignallevel"	"2"

			"paintbackground"	"0"
			
			"image_drawcolor"	"99 36 33 225"
			"image_armedcolor"	"154 30 22 225"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"12"
				"tall"			"12"
				"visible"		"1"
				"enabled"		"1"
				"image"			"../vgui/replay/thumbnails/circle"
				"scaleImage"	"1"
			}
		}
	}
}