"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Home.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Customization_Home_Panel"
			{
				"ControlName"							"EditablePanel"
				"FieldName"								"HUD_Customization_Home_Panel"
				"XPos"									"0"
				"YPos"									"0"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"3"
					"YPos"								"3"
					"ZPos"								"0"
					"Wide"								"f6"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"LabelText"							"Welcome to maxihud"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Description"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Description"
					"XPos"								"3"
					"YPos"								"30"
					"ZPos"								"0"
					"Wide"								"f6"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"LabelText"							"Select a category to navigate and apply the customizations"
					"Font"								"ItemFontNameLarge"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"50"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Warning_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Warning_Icon"
					"XPos"								"0"
					"YPos"								"61"
					"ZPos"								"0"
					"Wide"								"24"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"C"
					"Font"								"Symbols28"
					"TextAlignment"						"center"
					"FGColor"							"Red"
				}
				"Warning_1"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Warning_1"
					"XPos"								"28"
					"YPos"								"62"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"Wrap"								"1"
					"LabelText"							"Certain customizations will require a game restart in order to be fully applied, this will be indicated by the reload symbol!"
					"Font"								"ReplayMediumSmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"102"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Support_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Support_Icon"
					"XPos"								"0"
					"YPos"								"113"
					"ZPos"								"0"
					"Wide"								"24"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"^"
					"Font"								"Symbols28"
					"TextAlignment"						"center"
					"FGColor"							"QuestGold"
				}
				"Support_1"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Support_1"
					"XPos"								"28"
					"YPos"								"115"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"Wrap"								"1"
					"LabelText"							"Want to contribute to the HUD? Head to the GitHub page and feel free to make new suggestions, open new issues or contribute through pull requests!"
					"Font"								"ReplayMediumSmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_4"
					"XPos"								"3"
					"YPos"								"157"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Links_Desc"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Links_Desc"
					"XPos"								"5"
					"YPos"								"172"
					"ZPos"								"0"
					"Wide"								"130"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Check out maxihud on:"
					"Font"								"ReplayMediumSmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"GitHub_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"GitHub_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"^"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://github.com/maxiandrew/maxihud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"QuestGold"
					"ArmedFGColor_Override"				"208 147 75 150"
					"DepressedFGColor_Override"			"QuestGold"

					"Pin_To_Sibling"					"Links_Desc"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
				"ComfigHUDs_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"ComfigHUDs_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"n"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://comfig.app/huds/page/maxihud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"0 150 135 255"
					"ArmedFGColor_Override"				"0 100 90 255"
					"DepressedFGColor_Override"			"0 150 135 255"

					"Pin_To_Sibling"					"GitHub_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
				"TF2HUDs_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"TF2HUDs_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"0"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://tf2huds.dev/hud/maxihud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"255 85 0 255"
					"ArmedFGColor_Override"				"145 50 0 255"
					"DepressedFGColor_Override"			"255 85 0 255"

					"Pin_To_Sibling"					"ComfigHUDs_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
				"GameBanana_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"GameBanana_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"]"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://gamebanana.com/mods/459129"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"255 200 0 255"
					"ArmedFGColor_Override"				"160 125 0 255"
					"DepressedFGColor_Override"			"255 200 0 255"

					"Pin_To_Sibling"					"TF2HUDs_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
				"TFTV_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"TFTV_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"0"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"["
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://www.teamfortress.tv/34115/m0re-hud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"0 100 255 255"
					"ArmedFGColor_Override"				"0 140 255 255"
					"DepressedFGColor_Override"			"0 100 255 255"

					"Pin_To_Sibling"					"GameBanana_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
			}
		}
	}
}