#base "../../../cfg/maxihud/maxi_font.txt"
#base "../../../cfg/maxihud/maxi_color_health.txt"
#base "../../../cfg/maxihud/maxi_color_buff.txt"
#base "../../../cfg/maxihud/maxi_color_hurt.txt"
#base "../../../cfg/maxihud/maxi_color_clip.txt"
#base "../../../cfg/maxihud/maxi_color_reserve.txt"
#base "../../../cfg/maxihud/maxi_color_ammo_low.txt"
#base "../../../cfg/maxihud/maxi_color_uber.txt"
#base "../../../cfg/maxihud/maxi_color_uber_full.txt"
#base "../../../cfg/maxihud/maxi_color_shadows.txt"
#base "../../../cfg/maxihud/maxi_color_damage_last.txt"
#base "../../../cfg/maxihud/maxi_color_crosshair.txt"
#base "../../../cfg/maxihud/maxi_color_crosshair_flash.txt"
#base "../../../cfg/maxihud/maxi_color_hitmarker.txt"
#base "../../../cfg/maxihud/maxi_color_menu.txt"
#base "../../../cfg/maxihud/maxi_menu_theme.txt"
#base "clientscheme/base_scheme.res"
#base "clientscheme/border_scheme.res"
#base "clientscheme/color_scheme.res"
#base "clientscheme/font_scheme.res"
#base "crosshairs/crosshairs_scheme.res"
#base "../resource/crosshairs/crosshair_scheme.res"
#base "crosshairs/showcase_more.res"


