#base "clientscheme/base_scheme.res"
#base "clientscheme/border_scheme.res"
#base "clientscheme/color_scheme.res"
#base "clientscheme/font_scheme.res"
#base "../resource/customize_scheme.res"
#base "../resource/crosshairs/crosshair_scheme.res"