"Resource/UI/HudMedicCharge.res"
{	
	
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"25"
		"ypos"			"15"
		"zpos"			"2"
		"wide"			"96"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"textAlignment_minmode"	"east"		
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"HudFontGiantBold"
		"fgcolor"		"TanLight"
	}

	"IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"25"
		"xpos_minmode"	"95"
		"ypos"			"15"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_IndividualUberchargesMinHUD"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"HudFontGiantBold"
		"fgcolor"		"TanLight"
	}

	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"25"
		"ypos"			"55"
		"zpos"			"2"
		"wide"			"96"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}		

	"ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"25"
		"ypos"			"55"
		"zpos"			"2"
		"wide"			"22"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"50"
		"ypos"			"55"
		"zpos"			"2"
		"wide"			"22"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"75"
		"ypos"			"55"
		"zpos"			"2"
		"wide"			"22"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"100"
		"ypos"			"55"
		"zpos"			"2"
		"wide"			"22"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	
	"ChargeLabelSmall"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabelSmall"
		"xpos"					"0"
		"xpos_minmode"			"0"
		"ypos"					"24"
		"ypos_minmode"			"24"
		"zpos"					"2"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_UberchargeMinHUD"
		"labelText_minmode"		"#TF_UberchargeMinHUD"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"Default"
	}
	
	"ChargeLabelSmallBlur"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabelSmallBlur"
		"xpos"					"0"
		"xpos_minmode"			"0"
		"ypos"					"24"
		"ypos_minmode"			"24"
		"zpos"					"2"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_UberchargeMinHUD"
		"labelText_minmode"		"#TF_UberchargeMinHUD"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"DefaultBlur"
		"fgcolor_override"  	"CustomBlack"
	}
	
	"ChargeLabelSmallBlur2"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabelSmallBlur2"
		"xpos"					"0"
		"xpos_minmode"			"0"
		"ypos"					"24"
		"ypos_minmode"			"24"
		"zpos"					"2"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_UberchargeMinHUD"
		"labelText_minmode"		"#TF_UberchargeMinHUD"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"DefaultBlur"
		"fgcolor_override"  	"CustomBlack"
	}
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"2"
		"ypos"			"17"
		"wide"			"35"
		"tall"			"35"
		"visible"		"0"
		"visible_minmode"		"0"
		"enabled"		"0"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"	"1"	
	}

	"pinner"
	{
		"ControlName"  	"Panel"
		"xpos"  		"53"
		"xpos_minmode"	"58"
		"ypos"  		"16"
	}	
	
	"ResistIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"ResistIcon"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"35"
		"tall"				"35"
		"visible"			"1"
		"enabled"			"1"
		"image"				"../HUD/defense_buff_bullet_blue"
		"pin_to_sibling"	"pinner"
		"scaleImage"		"1"	
	}
	
	"MedigunChargeShadow"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"MedigunChargeShadow"
		"xpos"			"-25"
		"ypos"			"-60"
		"zpos"			"0"
		"wide"			"200"
		"tall"			"200"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"replay/thumbnails/hud/shadow_medigun"
	}	
}
