#base "../../../../cfg/maxihud/maxi_health_style.txt"
#base "../../../../cfg/maxihud/maxi_health_font.txt"
#base "../../../../cfg/maxihud/maxi_health_warning.txt"
#base "../../../../cfg/maxihud/maxi_health_fullscreen.txt"
#base "../../../../cfg/maxihud/maxi_resolution_scoreboard.txt"
#base "../../../cfg/maxihud/maxi_resolution_scoreboard.txt"
#base "fallback/hudplayerhealth.res"