#base "../ui/main_menu/menu_general.res"
#base "../ui/main_menu/menu_maxihudinfo.res"
#base "../ui/main_menu/menu_musicplayer.res"
#base "../ui/main_menu/menu_specialbuttons.res"
#base "../ui/main_menu/menu_maxihudsettings.res"