#base "MatchMakingDashboardSidePanel.res"

"Resource/UI/MatchMakingDashboardCompAccess.res"
{
	"CompAccess"
	{
		"fieldName"		"CompAccess"
		"xpos"			"r0"
		"ypos"			"10"
		"zpos"			"1001"
		"wide"			"290"
		"tall"			"f70"
		"visible"		"1"
		"proportionaltoparent"	"1"
		
		"TitleLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"Title"
			"xpos"		"8"
			"ypos"		"15"
			"zpos"		"99"
			"wide"		"f0"
			"tall"		"30"
			"proportionaltoparent"	"1"
			"labeltext"		"Quickplay"
			"textAlignment"	"west"
			"font"			"HudFontMediumBigBold"
			"fgcolor_override"	"TanDark"
			"mouseinputenabled"	"0"
		}
		
		"PickGamemodeLabel"		//GAMEMODE SELECTION LABEL
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PickGamemodeLabel"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"Play QuickGames!"
			"textAlignment"	"west"
			"xpos"			"9"
			"ypos"			"48"
			"zpos"			"51"
			"wide"			"240"
			"tall"			"18"
			"proportionaltoparent"	"1"
			"autoResize"	"1"
			"pinCorner"		"0"
			"visible"		"1"
			//"fgcolor_override"	"201 79 57 255"
			//"fgcolor_override"	"188 180 158 255"
			//"fgcolor_override"	"0 0 0 240"
			"enabled"		"1"
		}
		
		"BigScrollerGamemodesInnerShadow"		//FIX TO GET THE RIM SHADOW WORKING, PROPORTIONAL TO CONTAINER INSTEAD OF MAKING IT PROPORTIONAL TO THE SCROLLER BC IM LAZY
		{
			"ControlName"				"EditablePanel"
			"fieldName"					"BigScrollerGamemodesInnerShadow"
            "xpos"          "8"
            "ypos"          "70"
            "zpos"          "199"
			"tall"			"317"
			"wide"			"250"
			"mouseinputenabled"		"0"
			"proportionaltoparent"		"1"
			//"bgcolor_override"	"0 0 0 128"
			"bgcolor_override"	"0 0 0 0"
			"border"        "InnerShadowBorder"
		}
		
		"BigScrollerGamemodes"	//PARENT OF ALL GAMEMODES -------------------------------------------------------------------------------------------------------------------------------
		{
			"ControlName"				"CScrollableList"
			"fieldName"					"BigScrollerGamemodes"
            "xpos"          "8"
            "ypos"          "70"
            "zpos"          "199"
			"tall"			"317"
			"wide"			"250"
			"proportionaltoparent"		"1"
			//"bgcolor_override"	"0 0 0 128"
			"bgcolor_override"	"0 0 0 255"
			"border"        "InnerShadowBorder"
			
			"ScrollBar"
			{
				"ControlName"				"Scrollbar"
				"FieldName"					"ScrollBar"
				"xpos"						"r6"
				"tall"						"f0"
				"wide"						"5"	// This gets slammed from client schme.  GG.
				"zpos"						"1000"
				"nobuttons"					"1"
				"proportionaltoparent"		"1"
				"Slider"
				{
					"bgcolor_override"		"black"
					"fgcolor_override"	"TanDark"
				}
				"UpButton"
				{
					"ControlName"		"Button"
					"FieldName"			"UpButton"
					"visible"			"0"
				}
				"DownButton"
				{
					"ControlName"		"Button"
					"FieldName"			"DownButton"
					"visible"			"0"
				}
			}
		
			"ContainerForGamemodes"	//TALL WILL NEED TO BE ADJUSTED DEPENDING ON NUMBER OF GAMEMODES
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"ContainerForGamemodes"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"469"		//change this ifu change height
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
				
					"CoreGameModesBGPanel"
				{
					"fieldName"			"CareGameModesBGPanel"
					"ControlName"		"EditablePanel"
					"xpos"				"-4"
					"ypos"				"-2"
					"wide"				"280"
					"tall"				"26"

					"proportionaltoparent"	"1"
					"border"		"MainMenuBGBorder"
					
					"CoreModesLabel"
					{
						"ControlName"		"CExLabel"
						"fieldName"		"CoreModesLabel"
						"xpos"		"10"
						"ypos"		"3"
						"zpos"		"3"
						"wide"		"230"
						"tall"		"20"
						"proportionaltoparent"	"1"
						"labeltext"		"#CoreModesLabel"
						"smallcheckimage"	"1"
						"fgcolor"	"TanLight"	
						"font"		"HudFontSmallBold"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"3"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "20"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=attack_defense,ctf,capture_point,koth,payload,&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		">"
						"textAlignment"	"west"
						"font"	"HudFontSmallBold"
						"textinsetx"	"538"
						"textinsety"	"2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"117 107 94 200"
						"armedFgColor_override"		"TanLight"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
					}
					
				}
				
				"ADContainer"	//ATTACK DEFENSE
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"ADContainer"
					"xpos"					"0"
					//"ypos"					"0"
					"ypos"					"22"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
		
					"GrayBar"	//GRAY SPACER BAR ABOVE GAMEMODE
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"3"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"casual/gametype_ad"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}

					"GamemodePictureBlackBGFix"		//BLACK BACKGROUND FOR GAMEMODE
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"3"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}
					
					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Gametype_AttackDefense"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#TF_GameModeDesc_AttackDefense"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
					"enabled"		"1"
					}
					
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=attack_defense&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}
					
				"CTFContainer"	//CAPTURE THE FLAG
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"CTFContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"ADContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"casual/gametype_ctf"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Gametype_CTF"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#TF_GameModeDesc_CTF"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=ctf&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
					
				}	//End of CTFContainer
				
				"CPContainer"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"CPContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"CTFContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"casual/gametype_cp"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Gametype_CP"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#TF_GameModeDesc_CP"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
					"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=capture_point&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of CPContainer
			
				"KOTHContainer"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"KOTHContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"CPContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"casual/gametype_koth"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Gametype_KOTH"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#TF_GameModeDesc_Koth"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
					"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=koth&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of KOTHContainer
			
				"PLContainer"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"PLContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"KOTHContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"casual/gametype_payload"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Gametype_Escort"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#TF_GameModeDesc_Escort"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
					"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://comfig.app/quickplay/?autostart=1&gm=payload&autoclose=1"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of PLContainer
				
				"GrayBarCloser"			//little tab under payload mode
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"GrayBarCloser"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-11"
					"wide"					"250"
					"tall"					"p0.0047"			//ABSOLUTE PSYCHOSIS
					"visible"				"1"
					"enabled"				"1"
					"bgcolor_override"	"50 50 50 255"
					"proportionaltoparent"	"1"
					"mouseinputenabled"		"0"
					"pin_to_sibling"	"PLContainer"
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
				}
				
				"AltGamemodesContainer"	//fix for the shitty border on the alt gamemodes label box

				{
					"ControlName"			"EditablePanel"
					"fieldName"				"AltGamemodesContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"250"	//this needs to be changed if gms are added or removed
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					
					"pin_to_sibling"	"GrayBarCloser"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
				
					"ALTGameModesBGPanel"
					{
						"fieldName"			"ALTGameModesBGPanel"
						"ControlName"		"EditablePanel"
						"xpos"				"-4"
						"ypos"				"-2"
						"wide"				"280"
						"tall"				"26"
						"proportionaltoparent"	"1"
						"border"		"MainMenuBGBorder"
					}
					
					"AltModesLabel"
					{
						"ControlName"		"CExLabel"
						"fieldName"		"AltModesLabel"
						"xpos"		"10"
						"ypos"		"3"
						"zpos"		"3"
						"wide"		"230"
						"tall"		"20"
						"proportionaltoparent"	"1"
						"labeltext"		"#AltModesLabel"
						"smallcheckimage"	"1"
						"fgcolor"	"TanLight"	
						"font"		"HudFontSmallBold"
					}

					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"3"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "20"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       ""
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		""
						"textAlignment"	"west"
						"font"	"HudFontSmallBold"
						"textinsetx"	"538"
						"textinsety"	"2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"117 107 94 200"
						"armedFgColor_override"		"TanLight"
						"sound_depressed"   ""
						"sound_released"    "" 
						"sound_armed"		""
						"paintbackground"   "0"
					}
			
					"PLRContainer"
					{
					"ControlName"			"EditablePanel"
					"fieldName"				"PLRContainer"
					"xpos"					"0"
					"ypos"					"22"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"CTFImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"3"			//first one is different bc of fucky spacing
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"../vgui/replay/thumbnails/quickplay/uncletopia"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"3"				//first one is diff bc of fucky spacing
						"zpos"					"-11"		
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Server1Label"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#Server1DescriptionLabel"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://uncletopia.com/servers"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of PLRContainer
		
				"ArenaContainer"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"ArenaContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"PLRContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"CTFImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"../vgui/replay/thumbnails/quickplay/zestyjesus"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Server2Label"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#Server2DescriptionLabel"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://zestyjesus.com/servers.php"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of ArenaContainer
		
				"MiscContainer"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"MiscContainer"
					"xpos"					"0"
					"ypos"					"0"
					"zpos"					"-10"
					"wide"					"250"
					"tall"					"53"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"pin_to_sibling"	"ArenaContainer"	// PIN TO SIBLING TO STACK THE GAMEMODES, WAY EASIER THAN DOING MATH
					"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		
					"GrayBar"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GrayBar"
						"xpos"					"0"
						"ypos"					"0"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"3"
						"visible"				"1"
						"enabled"				"1"
						"bgcolor_override"	"50 50 50 255"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
			
					"GamemodePicture"
					{
						"ControlName"			"CTFImagePanel"
						"fieldName"				"GamemodePicture"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-10"
						"wide"					"200"
						"tall"					"51"
						"visible"				"1"
						"enabled"				"1"
						"image"					"../vgui/replay/thumbnails/quickplay/castaway"
						"scaleImage"			"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"0"
					}
					
					"GamemodePictureBlackBGFix"
					{
						"ControlName"			"EditablePanel"
						"fieldName"				"GamemodePictureBlackBGFix"
						"xpos"					"0"
						"ypos"					"4-1-1"
						"zpos"					"-11"
						"wide"					"250"
						"tall"					"50"
						"visible"				"1"
						"enabled"				"1"
						"scaleImage"			"0"
						"proportionaltoparent"	"1"
						"bgcolor_override"	"0 0 0 255"
						"mouseinputenabled"		"0"
					}

					"GamemodeTitleText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeTitleText"
						"font"			"HudFontSmallestBold"
						"labelText"		"#Server3Label"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"7"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
		
					"GamemodeDescriptionText"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"GamemodeDescriptionText"
						"font"			"MMenuPlayListDesc"
						"labelText"		"#Server3DescriptionLabel"
						"textAlignment"	"north-west"
						"xpos"			"r127"
						"ypos"			"20"
						"zpos"			"3"
						"tall"			"40"
						"wide"			"120"
						"proportionaltoparent"	"1"
						"autoResize"	"0"
						"wrap"			"1"
						"pinCorner"		"0"
						"visible"		"1"
						"enabled"		"1"
					}
				
					"FindAGameLabel"	//stupid hack
					{
						"ControlName"	"CExLabel"
						"fieldName"		"FindAGameLabel"
						"xpos"			"0"
						"ypos"			"rs1+1"
						"zpos"			"251"
						"wide"			"f0"
						"tall"			"10"
						"labeltext"		"#FindAGameLabel"
						"textAlignment"	"west"
						//"textAlignment"	"south"
						"font"	"MMenuPlayListDesc"
						"textinsetx"	"430"
						"visible"		"1"
						"enabled"		"1"
						"eatmouseinput"	"0"
						"mouseinputenabled"	"0"

						"proportionaltoparent"	"1"
					}
					
					"AutoQueueButton"		//GREEN URL BUTTON
					{
						"ControlName"   "CExImageButton"
						"fieldName"     "AutoQueueButton"
						"xpos"          "0"
						"ypos"			"5"
						"zpos"			"250"
						"wide"			"252"
						"tall"          "48"
						"autoResize"    "0"
						"pinCorner"     "3"
						"visible"       "1"
						"enabled"       "1"
						"command"       "url https://castaway.tf/"
						"tabPosition"   "0"
						"proportionaltoparent" "1"
						"labeltext"		"•"
						"textAlignment"	"south-west"
						"font"	"HudHintText"
						"textinsetx"	"12"
						"textinsety"	"-2"
						"dulltext"      "0"
						"brighttext"    "0"
						"default"       "1"
						"eatmouseinput"	"0"
						"actionsignallevel" "2"
						"defaultFgColor_override"	"45 45 45 0"
						"armedFgColor_override"		"255 255 255 255"
						"sound_depressed"   "UI/buttonclick.wav"
						"sound_released"    "UI/buttonclickrelease.wav" 
						"sound_armed"		"ui/item_info_mouseover.wav"
						"paintbackground"   "0"
						"image_default"		"../vgui/replay/thumbnails/background_gray"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"0"
							"ypos"			"rs1"
							"zpos"			"0"
							"wide"			"f0"
							"tall"			"9"
							"visible"		"1"
							"enabled"		"1"
							"scaleImage"	"1"
							
							"proportionaltoparent"	"1"
						}	
					}
					
					"BottomClickBlocker"
					{
						"ControlName"			"ImagePanel"
						"fieldName"				"BottomClickBlocker"
						"xpos"					"0"
						"ypos"					"rs1"
						"zpos"					"255"
						"wide"					"250"
						"paintbackground"   	"1"
						"tall"					"4"
						"visible"				"1"
						"enabled"				"1"
						"proportionaltoparent"	"1"
						"mouseinputenabled"		"1"
					}
				}	//End of MiscContainer
			}	
		}	//END OF SCROLLER
	}
	
	"TeamworkDotTF"
    {
		"ControlName"   "CExImageButton"
        "fieldName"     "TeamworkDotTF"
        "xpos"          "20"
		"ypos"			"r20"
		"zpos"			"210"
		"wide"			"95"
		"tall"          "18"
		"autoResize"    "0"
        "visible"       "1"
        "enabled"       "1"
		"command"       "url https://teamwork.tf"
		"labelText"     "    Teamwork.TF"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
        "tabPosition"   "0"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"proportionaltoparent"	"1"
		"image_drawcolor"	"235 226 202 255"
		"image_armedcolor"	"235 226 202 255"

		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"2"
			"ypos"			"2"
			"zpos"			"1"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../vgui/replay/thumbnails/quickplay/teamwork_icon"
			"scaleImage"	"1"
        }
	}
	
	"ConfigQuickplay"
    {
		"ControlName"   "CExImageButton"
        "fieldName"     "ConfigQuickplay"
        "xpos"          "r145"
		"ypos"			"r20"
		"zpos"			"210"
		"wide"			"120"
		"tall"          "18"
		"autoResize"    "0"
        "visible"       "1"
        "enabled"       "1"
		"command"       "url https://comfig.app/quickplay"
		"labelText"     "    Config Quickplay"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
        "tabPosition"   "0"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"proportionaltoparent"	"1"
		"image_drawcolor"	"235 226 202 255"
		"image_armedcolor"	"235 226 202 255"

		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"2"
			"ypos"			"2"
			"zpos"			"1"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../vgui/replay/thumbnails/quickplay/config_icon"
			"scaleImage"	"1"
        }		
	}

	"CompAccessEmbedded"
	{
		"ControlName"	"CCompetitiveAccessInfoPanel"
		"fieldName"		"CompAccessEmbedded"
		"xpos"			"5"
		"ypos"			"10"
		"zpos"			"1001"
		"wide"			"280"
		"tall"			"f10"
		"visible"		"0"
		"proportionaltoparent"	"1"
	}
}
